server:
  port: 8080
  address: localhost

base:
  url: http://localhost:8080/

spring:
  datasource:
    url: jdbc:h2:file:./habittracker-db
  mail:
    enabled: false
    host: smtp.gmail.com
    port: 587
    username: <mail-username>
    password: <mail-password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  security:
    basic-auth-users:
      test: $2y$10$/wEejER9Sbkiq2Sa/r7.KO0gier8wyXRaVze79pomeD7DxVCjV4n. # password: PASSWORD
      test2: $2y$10$/wEejER9Sbkiq2Sa/r7.KO0gier8wyXRaVze79pomeD7DxVCjV4n. # password: PASSWORD
      test3: $2y$10$/wEejER9Sbkiq2Sa/r7.KO0gier8wyXRaVze79pomeD7DxVCjV4n. # password: PASSWORD
      test4: $2y$10$/wEejER9Sbkiq2Sa/r7.KO0gier8wyXRaVze79pomeD7DxVCjV4n. # password: PASSWORD
      test5: $2y$10$/wEejER9Sbkiq2Sa/r7.KO0gier8wyXRaVze79pomeD7DxVCjV4n. # password: PASSWORD

management:
  endpoints:
    web:
      exposure:
        include: health,info,quartz,scheduledtasks

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    de.jofoerster: DEBUG

jwt.secret: T0M8xk85GC3/oOtdEcK++ZYtKKQL7ftrlXDtR4t09dBTqmnxCM+xoEEIdfAwIdEXRLiyGVCx2Z0utBYZcnLR6A==




