server:
  port: 8080
  address: localhost

base:
  url: http://localhost:8080/

spring:
  datasource:
    url: jdbc:h2:file:./habittracker-db
  mail:
    host: smtp.gmail.com
    port: 587
    username: <mail-username>
    password: <mail-password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  security:
    basic-auth-users:
      test: $2y$10$TxDKMLg7CtRNBG1ogewyPeGUKup6XqsfNfuvTZa7sLByJoFEWY9E6

management:
  endpoints:
    web:
      exposure:
        include: health,info,quartz,scheduledtasks

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt.secret: T0M8xk85GC3/oOtdEcK++ZYtKKQL7ftrlXDtR4t09dBTqmnxCM+xoEEIdfAwIdEXRLiyGVCx2Z0utBYZcnLR6A==




