CREATE TABLE api_key
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_authentication_id VARCHAR(255),
    hashed_key                VARCHAR(255),
    CONSTRAINT pk_apikey PRIMARY KEY (id)
);

CREATE TABLE api_key_authorities
(
    api_key_id BIGINT NOT NULL,
    authority  VARCHAR(255)
);

ALTER TABLE api_key
    ADD CONSTRAINT FK_APIKEY_ON_ACCOUNT_AUTHENTICATIONID FOREIGN KEY (account_authentication_id) REFERENCES account (authentication_id);

ALTER TABLE api_key_authorities
    ADD CONSTRAINT fk_api_key_authorities_on_api_key FOREIGN KEY (api_key_id) REFERENCES api_key (id);