-- Rename the existing content field to htmlContent in the Notification table
ALTER TABLE  PUBLIC.NOTIFICATION ALTER COLUMN CONTENT RENAME TO HTML_CONTENT;

-- Create a new content field as TEXT
ALTER TABLE PUBLIC.NOTIFICATION
ADD COLUMN CONTENT CHARACTER VARYING;

-- create new content template field
ALTER TABLE PUBLIC.NOTIFICATION_TEMPLATE
ADD COLUMN CONTENT_TEMPLATE_NAME CHARACTER VARYING(255);